name: Test
on:
    release:
        types:
            - created
jobs:
    release:
        name: Release - ${{ matrix.platform.release_for }}
        strategy:
            matrix:
                platform:
                    - release_for: Windows-x86_64
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      bin: fgddem.exe
                      name: fgddem-Windows-x86_64.zip
                      command: both

                    - release_for: macOS-arm64
                      os: macOS-latest
                      target: aarch64-apple-darwin
                      bin: fgddem
                      name: fgddem-macOS-arm64.tar.gz
                      command: both

        runs-on: ${{ matrix.platform.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install libgdal-dev
              run: |
                  sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
                  sudo apt-get update
                  sudo apt-get install gdal-bin libgdal-dev
            - name: Build binary
              uses: houseabsolute/actions-rust-cross@v0
              with:
                  command: ${{ matrix.platform.command }}
                  target: ${{ matrix.platform.target }}
                  args: '--locked --release'
                  strip: true
            - name: Create zip archive
              run: |
                  tar -czf ${{ matrix.platform.name }} target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
            - name: Upload release asset
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release upload ${{ github.event.release.tag_name }} ${{ matrix.platform.name }}
