name: Test

on:
    push:
        branches:
            - main
        tags:
            - '*'
    pull_request:

env:
    CARGO_TERM_COLOR: always

permissions:
    contents: read

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain:
                    - stable
        steps:
            - uses: actions/checkout@v4
            - name: Rustup
              run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov
            - name: install libgdal-dev
              run: |
                  sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
                  sudo apt-get update
                  sudo apt-get install gdal-bin libgdal-dev
            - name: Build
              run: cargo build --verbose
            - name: Test
              run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
